apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: project-controller
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/project-controller/project-controller@sha256:243fd11619d320e836b312f2c0aeed8f42716bfa58568dd431007233c2f3f964
        name: container-image
        resources: {}
status: {}
