apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: project-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: project-controller
    app.kubernetes.io/part-of: project-controller
  name: project-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: project-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: project-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/project-controller/project-controller@sha256:1dd111cb0db26eb309a079e160ec2d5cd3483fec1e21d12caa1897af4bf86f98
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
